name: Comment Trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  process_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '14'
    
    - name: Check if commenter is organization member
      id: org-check
      run: |
        COMMENTER_LOGIN=$(jq -r .comment.user.login "$GITHUB_EVENT_PATH")
        ORG="bokulich-lab"
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.ORG_ACCESS_TOKEN }}" "https://api.github.com/orgs/$ORG/members/$COMMENTER_LOGIN")
        if [[ "$RESPONSE" == *"Not Found"* ]]; then
          echo "Commenter is not a member of the organization."
          exit 1
        else
          echo "Commenter is a member of the organization."
        fi
    
    - name: Process Comment
      id: process-comment
      if: contains(github.event.comment.body, '/approved ontology string:')
      run: |
          COMMENT_BODY=$(jq -r .comment.body "$GITHUB_EVENT_PATH")
          ONTOLOGY_STRING=$(echo "$COMMENT_BODY" | grep -oP '(?<=/approved ontology string:)[^\s]+')
          echo "::set-output name=ontology_string::$ONTOLOGY_STRING"


    
      


          
    
