name: Comment Trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  process_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '14'
    
    - name: Check if commenter is organization member
      id: org-check
      run: |
        COMMENTER_LOGIN=$(jq -r .comment.user.login "$GITHUB_EVENT_PATH")
        ORG="bokulich-lab"
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.ORG_ACCESS_TOKEN }}" "https://api.github.com/orgs/$ORG/members/$COMMENTER_LOGIN")
        if [[ "$RESPONSE" == *"Not Found"* ]]; then
          echo "Commenter is not a member of the organization."
          exit 1
        else
          echo "Commenter is a member of the organization."
        fi
    
    - name: Process Comment
      id: process-comment
      if: contains(github.event.comment.body, '/approved ontology string:')
      run: |
          COMMENT_BODY=$(jq -r .comment.body "$GITHUB_EVENT_PATH")
          ONTOLOGY_STRING=$(echo "$COMMENT_BODY" | grep -oP '(?<=/approved ontology string:)[^\s]+')
          echo "Ontology string: $ONTOLOGY_STRING"
          echo "::set-output name=ontology_string::$ONTOLOGY_STRING"

    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x' 
    
    - name: Execute Python script
      if: steps.process-comment.outputs.ontology_string
      run: |
          python3 process_json.py
      env:
          ONTOLOGY_STRING: ${{ steps.process-comment.outputs.ontology_string }}
          JSON_FILE_PATH: ${{ github.workspace }}/fermented_food_ontology.json  
    
    - name: Commit changes
      if: steps.process-comment.outputs.ontology_string
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-ontology-${{ steps.process-comment.outputs.ontology_string }}
          git add ${{ env.JSON_FILE_PATH }}
          git commit -m "Update ontology JSON, new entry: ${{ steps.process-comment.outputs.ontology_string }}"
          git push origin update-ontology-${{ steps.process-comment.outputs.ontology_string }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      if: steps.process-comment.outputs.ontology_string
      uses: peter-evans/create-pull-request@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update ontology JSON, new entry: ${{ steps.process-comment.outputs.ontology_string }}"
          branch: update-ontology-${{ steps.process-comment.outputs.ontology_string }}
          title: "Update ontology JSON, new entry: ${{ steps.process-comment.outputs.ontology_string }}"
          body: "This PR updates the ontology JSON file with a new entry."
          base: main

    
      


          
    
